version: '2'
services:
  govpay:
    container_name: govpay_3.6.0_mysql
    image: linkitaly/govpay:3.6.0_mysql
    depends_on:
        - database
    ports:
        - 8080:8080
    volumes:
        - ./govpay_log:/var/log/govpay
        # Il driver deve essere compiato manualmente nella directory corrente
        - ./mysql-connector-java-8.0.29.jar:/tmp/mysql-connector-java-8.0.29.jar 
    environment:
        - GOVPAY_DB_SERVER=my_govpay_3.6.0_mysql
        - GOVPAY_DB_NAME=govpaydb
        - GOVPAY_DB_USER=govpay
        - GOVPAY_DB_PASSWORD=govpay
        - GOVPAY_MYSQL_JDBC_PATH=/tmp/mysql-connector-java-8.0.29.jar
        - GOVPAY_POP_DB_SKIP=false
  database:
    container_name: my_govpay_3.6.0_mysql
    image: mariadb:10.6
    environment:
      - MARIADB_DATABASE=govpaydb
      - MARIADB_USER=govpay
      - MARIADB_PASSWORD=govpay
      - MARIADB_ROOT_PASSWORD=my-secret-pw
    ports:
       - 3306:3306
